services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: ${DB_USER}    
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}  
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: nginx:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
